# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8cf15d14026fc09b92c6d39a5f40095c01cf5f66b38becbd00ed4ef9e146a4346c97b9033bacf6c18a82bf298f29f0b9c630a84bd43c972637e79ca5826bdf8

test:
  secret_key_base: bf95b705befa699d8240ab58998f81debe4c00b45b25aa602835e7e44222e4fedc40fc32910f4cc705991a23ef48dccdafb4e6309c7d5cd82808344ab554bf57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
